export interface GameDefinition {
  id: string;
  name: string;
  emoji: string;
  category: 'word' | 'number' | 'logic' | 'visual' | 'classic';
  tagline: string;
  description: string;
  difficulty: 'easy' | 'medium' | 'hard' | 'variable';
  estimatedMinutes: number;
  isUnlimited: boolean;
  hasDailyMode: boolean;
  mvpPhase: number;
  hint: string;
}

export const GAMES: GameDefinition[] = [
  {
    id: 'sudoku',
    name: 'Sudoku Classic',
    emoji: '🔢',
    category: 'number',
    tagline: 'Fill the 9×9 grid with digits 1–9',
    description: 'Each row, column, and 3×3 box must contain digits 1–9 exactly once. No repeats allowed.',
    difficulty: 'variable',
    estimatedMinutes: 10,
    isUnlimited: true,
    hasDailyMode: true,
    mvpPhase: 1,
    hint: 'Look for rows, columns, or boxes with the most digits filled. A cell with only one possibility must be that digit.',
  },
  {
    id: 'word-guess',
    name: 'Word Guess',
    emoji: '🟩',
    category: 'word',
    tagline: 'Guess the hidden word in 6 tries',
    description: '5-letter word. Green = right letter, right spot. Yellow = right letter, wrong spot. Gray = not in the word. 6 attempts to get it.',
    difficulty: 'variable',
    estimatedMinutes: 3,
    isUnlimited: true,
    hasDailyMode: true,
    mvpPhase: 2,
    hint: 'Start with a word rich in common letters like CRANE or SLATE. Green = right place, yellow = wrong place.',
  },
  {
    id: 'word-search',
    name: 'Word Search',
    emoji: '🔍',
    category: 'word',
    tagline: 'Find all hidden words in the grid',
    description: 'Letters hide 10 themed words going horizontal, vertical, or diagonal. Drag from the first letter to the last to find them.',
    difficulty: 'easy',
    estimatedMinutes: 5,
    isUnlimited: true,
    hasDailyMode: false,
    mvpPhase: 4,
    hint: 'Words go in 8 directions including diagonals. Scan each row slowly for the first letter of a word you are hunting.',
  },
  {
    id: 'group-it',
    name: 'Group It',
    emoji: '🔗',
    category: 'word',
    tagline: 'Find four groups of four related words',
    description: '16 words, 4 hidden categories. Find which four words share a connection. Yellow is easiest, purple is trickiest. Four mistakes allowed.',
    difficulty: 'variable',
    estimatedMinutes: 5,
    isUnlimited: false,
    hasDailyMode: true,
    mvpPhase: 5,
    hint: 'The trickiest group often uses an unexpected meaning. Common-looking words are usually the trap — think laterally.',
  },
  {
    id: 'hangman',
    name: 'Hangman',
    emoji: '🪢',
    category: 'word',
    tagline: 'Guess the word before the hangman is drawn',
    description: 'Letters hide a secret word. Guess one letter at a time — six wrong guesses and it\'s over. Can you crack the word in time?',
    difficulty: 'variable',
    estimatedMinutes: 3,
    isUnlimited: true,
    hasDailyMode: false,
    mvpPhase: 6,
    hint: 'Try frequent consonants first: R, S, T, L, N. Then common vowels A, E, I. Avoid rare letters like Q, Z, X.',
  },
  {
    id: 'number-bonds',
    name: 'Number Bonds',
    emoji: '🔢',
    category: 'number',
    tagline: 'Find pairs of numbers that sum to the target',
    description: 'Tap two numbers that add up to the target. Clear the whole board to win. Simple math, satisfying combos.',
    difficulty: 'easy',
    estimatedMinutes: 3,
    isUnlimited: true,
    hasDailyMode: false,
    mvpPhase: 6,
    hint: 'Start from the corners — corner tiles have fewer pairing options. Work inward as the board clears.',
  },
  {
    id: 'crossword-mini',
    name: 'Mini Crossword',
    emoji: '✏️',
    category: 'word',
    tagline: 'Classic crossword in a compact 5×5 grid',
    description: 'Fill in across and down answers based on clues. Tap a cell, pick a direction, and type. Complete the grid to win.',
    difficulty: 'medium',
    estimatedMinutes: 5,
    isUnlimited: true,
    hasDailyMode: true,
    mvpPhase: 7,
    hint: 'Tackle the shortest answers first — they narrow down the crossing letters for harder clues.',
  },
  {
    id: 'pattern-recog',
    name: 'Pattern Match',
    emoji: '🔭',
    category: 'logic',
    tagline: 'What comes next in the pattern?',
    description: 'A sequence of shapes and colors. Study the pattern and pick the correct next item from four choices.',
    difficulty: 'variable',
    estimatedMinutes: 4,
    isUnlimited: true,
    hasDailyMode: false,
    mvpPhase: 7,
    hint: 'Each attribute (color, shape, size, count) may cycle independently. Track them one at a time.',
  },
  {
    id: 'sequence-fill',
    name: 'Sequence Fill',
    emoji: '🌀',
    category: 'number',
    tagline: 'Complete the number sequence',
    description: 'Arithmetic, geometric, Fibonacci, squares — fill the blanks to complete each number pattern. 8 sequences per round.',
    difficulty: 'variable',
    estimatedMinutes: 4,
    isUnlimited: true,
    hasDailyMode: false,
    mvpPhase: 7,
    hint: 'Find the gap between consecutive numbers. Constant gap = arithmetic. Constant multiplier = geometric.',
  },
  {
    id: 'math-sprint',
    name: 'Math Sprint',
    emoji: '⚡',
    category: 'number',
    tagline: 'Answer 20 math questions as fast as possible',
    description: 'Rapid-fire arithmetic. Addition, subtraction, multiplication, division. Wrong answers cost you time. How fast can you go?',
    difficulty: 'variable',
    estimatedMinutes: 2,
    isUnlimited: true,
    hasDailyMode: false,
    mvpPhase: 7,
    hint: 'Trust your instinct for small numbers. For larger ones, break them: 12×13 = 12×10 + 12×3 = 156.',
  },
  // MVP 8
  {
    id: 'anagram',
    name: 'Anagram',
    emoji: '🔀',
    category: 'word',
    tagline: 'Unscramble the letters to find the word',
    description: 'Letters are shuffled — rearrange them to spell the hidden word. Race against the clock across multiple rounds.',
    difficulty: 'variable',
    estimatedMinutes: 3,
    isUnlimited: true,
    hasDailyMode: false,
    mvpPhase: 8,
    hint: 'Rearrange consonants around the vowels. Try common word endings like -ING, -ED, or -ER first.',
  },
  {
    id: 'compound-words',
    name: 'Compound Words',
    emoji: '🔗',
    category: 'word',
    tagline: 'Combine two words into one compound word',
    description: 'Pick the right pair of words that combine to form a valid compound word. 10 rounds of word combining fun.',
    difficulty: 'easy',
    estimatedMinutes: 3,
    isUnlimited: true,
    hasDailyMode: false,
    mvpPhase: 8,
    hint: 'Think of two shorter words that can merge. The first word usually modifies or belongs with the second.',
  },
  {
    id: 'game-2048',
    name: '2048',
    emoji: '🔢',
    category: 'number',
    tagline: 'Swipe to merge tiles and reach 2048',
    description: 'Swipe in any direction to slide all tiles. When two tiles with the same number collide they merge. Reach 2048 to win.',
    difficulty: 'medium',
    estimatedMinutes: 10,
    isUnlimited: true,
    hasDailyMode: false,
    mvpPhase: 8,
    hint: 'Keep your highest tile in one corner. Build a chain from that corner outward and never move away from it.',
  },
  {
    id: 'kakuro',
    name: 'Kakuro',
    emoji: '➕',
    category: 'number',
    tagline: 'Cross-sum number puzzle',
    description: 'Fill digits 1–9 so each run sums to its clue. No digit repeats within a run. The number crossword.',
    difficulty: 'hard',
    estimatedMinutes: 15,
    isUnlimited: true,
    hasDailyMode: false,
    mvpPhase: 8,
    hint: 'Cells in a run must be unique digits 1–9. List all combos that sum to the clue and eliminate impossible digits.',
  },
  {
    id: 'color-sort',
    name: 'Color Sort',
    emoji: '🎨',
    category: 'visual',
    tagline: 'Sort colored balls into matching tubes',
    description: 'Move balls between tubes so each tube contains only one color. You can only place a ball on top of one of the same color.',
    difficulty: 'medium',
    estimatedMinutes: 5,
    isUnlimited: true,
    hasDailyMode: false,
    mvpPhase: 8,
    hint: 'Only move the top ball of a tube. Avoid mixing different colors — free up a tube to use as a buffer.',
  },
  {
    id: 'pipe-connect',
    name: 'Pipe Connect',
    emoji: '🔩',
    category: 'logic',
    tagline: 'Connect all pipes to complete the circuit',
    description: 'Rotate pipe tiles so every endpoint is connected and no pipe leads to a dead end. Fill the whole board.',
    difficulty: 'medium',
    estimatedMinutes: 5,
    isUnlimited: true,
    hasDailyMode: false,
    mvpPhase: 8,
    hint: 'Start from the endpoints and work inward. Pipes that only fit one direction are your fixed anchors.',
  },
  {
    id: 'tower-of-hanoi',
    name: 'Tower of Hanoi',
    emoji: '🗼',
    category: 'logic',
    tagline: 'Move the stack to the rightmost peg',
    description: 'Move all discs from the left peg to the right peg. Only one disc at a time, and never place a larger disc on a smaller one.',
    difficulty: 'variable',
    estimatedMinutes: 5,
    isUnlimited: true,
    hasDailyMode: false,
    mvpPhase: 8,
    hint: 'Move smaller disks out of the way first. For N disks you need exactly 2ⁿ−1 moves minimum.',
  },
  {
    id: 'sliding-puzzle',
    name: 'Sliding Puzzle',
    emoji: '🧩',
    category: 'logic',
    tagline: 'Slide tiles to restore the image',
    description: 'Classic 15-puzzle. Slide numbered tiles into order 1–15 using the single empty space. Fewest moves wins.',
    difficulty: 'medium',
    estimatedMinutes: 10,
    isUnlimited: true,
    hasDailyMode: false,
    mvpPhase: 8,
    hint: 'Solve rows top to bottom. Use a circular motion to place the last two tiles in each row without disturbing earlier ones.',
  },
  // MVP 9
  {
    id: 'hidden-words',
    name: 'Hidden Words',
    emoji: '🔎',
    category: 'word',
    tagline: 'Find words hidden within sentences',
    description: 'Words are concealed inside longer phrases. Spot the hidden word spanning two adjacent words in each sentence.',
    difficulty: 'easy',
    estimatedMinutes: 4,
    isUnlimited: true,
    hasDailyMode: false,
    mvpPhase: 9,
    hint: 'Read across the boundaries between words — hidden words often span two adjacent words in the phrase.',
  },
  {
    id: 'word-chain',
    name: 'Word Chain',
    emoji: '⛓️',
    category: 'word',
    tagline: 'Link words where each shares letters with the next',
    description: 'Each word must share its last two letters with the start of the next. Build the longest chain you can.',
    difficulty: 'medium',
    estimatedMinutes: 5,
    isUnlimited: true,
    hasDailyMode: false,
    mvpPhase: 9,
    hint: 'Keep your options open. Pick transitions that connect to many possible next words, not just one obvious path.',
  },
  {
    id: 'word-ladder',
    name: 'Word Ladder',
    emoji: '🪜',
    category: 'word',
    tagline: 'Transform one word into another, step by step',
    description: 'Change one letter at a time to climb from the start word to the target word. Each step must be a valid word.',
    difficulty: 'medium',
    estimatedMinutes: 5,
    isUnlimited: true,
    hasDailyMode: false,
    mvpPhase: 9,
    hint: 'Change one letter at a time. Look for bridge words that share letters with both the start and end words.',
  },
  {
    id: 'minesweeper',
    name: 'Minesweeper',
    emoji: '💣',
    category: 'logic',
    tagline: 'Clear the minefield without hitting a bomb',
    description: 'Reveal cells using number clues that show how many adjacent mines there are. Flag suspected mines. Clear the board to win.',
    difficulty: 'variable',
    estimatedMinutes: 5,
    isUnlimited: true,
    hasDailyMode: false,
    mvpPhase: 9,
    hint: 'A number touching only one covered cell means that cell is definitely a mine — flag it safely.',
  },
  {
    id: 'magic-square',
    name: 'Magic Square',
    emoji: '✨',
    category: 'number',
    tagline: 'Every row, column and diagonal sums equally',
    description: 'Place numbers in the grid so every row, column, and diagonal adds up to the same magic sum.',
    difficulty: 'medium',
    estimatedMinutes: 8,
    isUnlimited: true,
    hasDailyMode: false,
    mvpPhase: 9,
    hint: 'The magic sum for a 3×3 square is 15. The center must be 5. Use this as your starting anchor.',
  },
  {
    id: 'balance-scales',
    name: 'Balance Scales',
    emoji: '⚖️',
    category: 'logic',
    tagline: 'Deduce weights using balance scale clues',
    description: 'Use the balance clues to figure out the weight of each item. Logic and deduction required.',
    difficulty: 'medium',
    estimatedMinutes: 5,
    isUnlimited: true,
    hasDailyMode: false,
    mvpPhase: 9,
    hint: 'Build a chain of comparisons. If A > B and B > C then A > C — reason transitively to find the order.',
  },
  {
    id: 'flood-fill',
    name: 'Flood Fill',
    emoji: '🌊',
    category: 'visual',
    tagline: 'Flood the board with one color',
    description: 'Tap colors to flood-fill from the top-left corner. Make the entire board one color in the fewest moves.',
    difficulty: 'medium',
    estimatedMinutes: 4,
    isUnlimited: true,
    hasDailyMode: false,
    mvpPhase: 9,
    hint: 'Plan 2–3 moves ahead. Choose a color that opens up the largest connected region for your next move.',
  },
  {
    id: 'maze-runner',
    name: 'Maze Runner',
    emoji: '🌀',
    category: 'logic',
    tagline: 'Navigate through the maze to the exit',
    description: 'Use the D-pad to guide your player through a randomly generated maze. Find the exit without hitting walls.',
    difficulty: 'variable',
    estimatedMinutes: 4,
    isUnlimited: true,
    hasDailyMode: false,
    mvpPhase: 9,
    hint: 'Mark dead ends as you backtrack. Always try the rightmost unvisited path first for a consistent strategy.',
  },
  {
    id: 'pixel-art',
    name: 'Pixel Art',
    emoji: '🎨',
    category: 'visual',
    tagline: 'Color the grid to reveal the hidden image',
    description: 'Follow the color guide to paint each cell. Fill in the grid correctly to reveal the pixel art.',
    difficulty: 'easy',
    estimatedMinutes: 5,
    isUnlimited: true,
    hasDailyMode: false,
    mvpPhase: 9,
    hint: 'Fill the dominant background color first. Work from the largest regions forward to the smallest details.',
  },
  {
    id: 'flag-quiz',
    name: 'Flag Quiz',
    emoji: '🚩',
    category: 'classic',
    tagline: 'Identify countries from their flags',
    description: 'A flag is shown — pick the correct country from four options. 10 rounds of world flags.',
    difficulty: 'variable',
    estimatedMinutes: 4,
    isUnlimited: true,
    hasDailyMode: false,
    mvpPhase: 9,
    hint: 'Focus on distinctive symbols, stripes, and color arrangements. Flags with unique emblems are easiest to lock in.',
  },
  {
    id: 'noughts-crosses',
    name: 'Noughts & Crosses',
    emoji: '❌',
    category: 'classic',
    tagline: 'Get 5 in a row on a 10×10 board',
    description: 'Classic Tic-Tac-Toe extended to a 10×10 grid. Be the first to connect 5 in a row horizontally, vertically, or diagonally.',
    difficulty: 'medium',
    estimatedMinutes: 5,
    isUnlimited: true,
    hasDailyMode: false,
    mvpPhase: 9,
    hint: 'Always take the center square if free. Try to create two threats simultaneously — your opponent can only block one.',
  },
  // MVP 10
  {
    id: 'boggle',
    name: 'Boggle',
    emoji: '🔤',
    category: 'word',
    tagline: 'Find as many words as possible in the letter grid',
    description: 'Trace adjacent letters to form words. Longer words score more. Find all the words before time runs out.',
    difficulty: 'variable',
    estimatedMinutes: 3,
    isUnlimited: true,
    hasDailyMode: false,
    mvpPhase: 10,
    hint: 'Start with short 3-letter words to find your footing, then look for -ING, -ER, and UN- prefixes for longer words.',
  },
  {
    id: 'rhyme-time',
    name: 'Rhyme Time',
    emoji: '🎵',
    category: 'word',
    tagline: 'Pick the word that rhymes with the prompt',
    description: 'Given a word, choose which of four options rhymes with it. 10 rounds of poetic matching.',
    difficulty: 'easy',
    estimatedMinutes: 3,
    isUnlimited: true,
    hasDailyMode: false,
    mvpPhase: 10,
    hint: 'Say the target word aloud — your ear often finds the rhyme before your eye does scanning the options.',
  },
  {
    id: 'backwards-words',
    name: 'Backwards Words',
    emoji: '🔁',
    category: 'word',
    tagline: 'Read words written backwards',
    description: 'Words are displayed in reverse. Can you read them quickly? 10 rounds of reversed word decoding.',
    difficulty: 'easy',
    estimatedMinutes: 3,
    isUnlimited: true,
    hasDailyMode: false,
    mvpPhase: 10,
    hint: 'Spell each word letter by letter in reverse out loud — hearing it backwards often reveals the word faster.',
  },
  {
    id: 'cryptogram',
    name: 'Cryptogram',
    emoji: '🔐',
    category: 'word',
    tagline: 'Decode the encrypted message',
    description: 'Each letter is substituted with another. Tap letters to assign your guesses and decode the famous quote.',
    difficulty: 'hard',
    estimatedMinutes: 10,
    isUnlimited: true,
    hasDailyMode: true,
    mvpPhase: 10,
    hint: 'Start with single-letter words (A or I), then common short words like THE, AND, or IS to anchor the cipher.',
  },
  {
    id: 'kenken',
    name: 'KenKen',
    emoji: '🔢',
    category: 'number',
    tagline: 'Math-based Latin square puzzle',
    description: 'Fill digits in a grid so each row and column has no repeats. Caged cells must satisfy the given math operation.',
    difficulty: 'hard',
    estimatedMinutes: 10,
    isUnlimited: true,
    hasDailyMode: false,
    mvpPhase: 10,
    hint: 'Small cages have very few digit combinations. List all possibilities for each cage before you start placing.',
  },
  {
    id: 'math-crossword',
    name: 'Math Crossword',
    emoji: '✏️',
    category: 'number',
    tagline: 'Fill in the number crossword',
    description: 'Like a crossword but with numbers. Across and down clues are math equations. Fill every cell correctly.',
    difficulty: 'medium',
    estimatedMinutes: 8,
    isUnlimited: true,
    hasDailyMode: false,
    mvpPhase: 10,
    hint: 'Work from cells shared by across and down entries — the intersection digit must satisfy both equations.',
  },
  {
    id: 'nonogram',
    name: 'Nonogram',
    emoji: '🖼️',
    category: 'logic',
    tagline: 'Reveal the picture using row and column clues',
    description: 'Shade cells based on the numeric clues for each row and column. The completed grid reveals a hidden picture.',
    difficulty: 'hard',
    estimatedMinutes: 15,
    isUnlimited: true,
    hasDailyMode: false,
    mvpPhase: 10,
    hint: 'Focus on rows or columns where the clues nearly fill the space — a clue of 5 in a 5-wide row must be solid.',
  },
  {
    id: 'hitori',
    name: 'Hitori',
    emoji: '⬛',
    category: 'logic',
    tagline: 'Shade cells so no number repeats in any row or column',
    description: 'Black out cells so no number appears twice in a row or column. Shaded cells cannot touch, and all white cells must stay connected.',
    difficulty: 'hard',
    estimatedMinutes: 10,
    isUnlimited: true,
    hasDailyMode: false,
    mvpPhase: 10,
    hint: 'A circled cell cannot be adjacent to another circled cell. Start by circling obvious duplicate numbers.',
  },
  {
    id: 'chess-puzzles',
    name: 'Chess Puzzles',
    emoji: '♟️',
    category: 'classic',
    tagline: 'Find checkmate in one or two moves',
    description: 'Classic chess positions where you must find the winning move. Mate in 1, mate in 2 — sharpen your tactics.',
    difficulty: 'variable',
    estimatedMinutes: 5,
    isUnlimited: true,
    hasDailyMode: false,
    mvpPhase: 10,
    hint: 'Look for checks, captures, and forks first. Most tactical puzzles end with forced checkmate or material gain.',
  },
  {
    id: 'science-symbols',
    name: 'Science Symbols',
    emoji: '⚗️',
    category: 'classic',
    tagline: 'Match science symbols to their meanings',
    description: 'Chemical elements, physics constants, math symbols — match each symbol to its correct name or meaning.',
    difficulty: 'variable',
    estimatedMinutes: 4,
    isUnlimited: true,
    hasDailyMode: false,
    mvpPhase: 10,
    hint: 'Group by shape and origin. Element symbols usually take the first letter or two of their Latin name.',
  },
  // MVP 11
  {
    id: 'word-hive',
    name: 'Word Hive',
    emoji: '🐝',
    category: 'word',
    tagline: 'Make words using the honeycomb letters',
    description: 'Tap letters in the hexagonal hive to spell words. The center letter must be in every word. Find the pangram to win.',
    difficulty: 'medium',
    estimatedMinutes: 8,
    isUnlimited: true,
    hasDailyMode: true,
    mvpPhase: 11,
    hint: 'The center letter must appear in every word. Try adding it to common endings like -ATE, -ING, or -ED.',
  },
  {
    id: 'missing-vowels',
    name: 'Missing Vowels',
    emoji: '🔤',
    category: 'word',
    tagline: 'Fill in the missing vowels to complete words',
    description: 'Words are shown with all vowels removed. Add the correct vowels to complete each word. 10 rounds.',
    difficulty: 'easy',
    estimatedMinutes: 4,
    isUnlimited: true,
    hasDailyMode: false,
    mvpPhase: 11,
    hint: 'Read the consonant string aloud quickly — your brain naturally fills in the missing vowels as you speak.',
  },
  {
    id: 'quote-guess',
    name: 'Quote Guess',
    emoji: '💬',
    category: 'word',
    tagline: 'Guess who said the famous quote',
    description: 'A famous quotation is displayed. Pick the correct author from four choices. Literature, history, science, and more.',
    difficulty: 'medium',
    estimatedMinutes: 4,
    isUnlimited: true,
    hasDailyMode: false,
    mvpPhase: 11,
    hint: 'Famous quotes often open with I, The, It, or You. Short common words give you the biggest initial footholds.',
  },
  {
    id: 'letter-soup',
    name: 'Letter Soup',
    emoji: '🍲',
    category: 'word',
    tagline: 'Form words from the circling letter bowl',
    description: 'Letters orbit the center. Tap letters in order to spell words. Find all target words before time runs out.',
    difficulty: 'medium',
    estimatedMinutes: 4,
    isUnlimited: true,
    hasDailyMode: false,
    mvpPhase: 11,
    hint: 'Read diagonally and backwards too. Common 3-letter words like THE, AND, FOR hide in surprising directions.',
  },
  {
    id: 'memory-match',
    name: 'Memory Match',
    emoji: '🃏',
    category: 'classic',
    tagline: 'Find all matching emoji pairs',
    description: 'Flip cards to find matching pairs. Remember where you saw each emoji. Match all pairs to win.',
    difficulty: 'variable',
    estimatedMinutes: 4,
    isUnlimited: true,
    hasDailyMode: false,
    mvpPhase: 11,
    hint: 'Group cards mentally by screen position. Flip cards from new regions to learn their faces before matching.',
  },
  {
    id: 'symbol-sequence',
    name: 'Symbol Sequence',
    emoji: '🔔',
    category: 'classic',
    tagline: 'Repeat the growing symbol sequence',
    description: 'Symbols light up in sequence. Watch carefully, then tap them back in the same order. How long can you remember?',
    difficulty: 'variable',
    estimatedMinutes: 3,
    isUnlimited: true,
    hasDailyMode: false,
    mvpPhase: 11,
    hint: 'Track each symbol property independently — some rotate, some flip. Focus on one attribute at a time.',
  },
  {
    id: 'peg-solitaire',
    name: 'Peg Solitaire',
    emoji: '🔵',
    category: 'logic',
    tagline: 'Jump pegs to clear the board',
    description: 'Jump one peg over an adjacent one to remove it. Clear all but one peg to win. The classic English board puzzle.',
    difficulty: 'hard',
    estimatedMinutes: 10,
    isUnlimited: true,
    hasDailyMode: false,
    mvpPhase: 11,
    hint: 'Plan jumps that leave pegs in positions to enable more jumps. The center peg is usually the last one standing.',
  },
  {
    id: 'skyscrapers',
    name: 'Skyscrapers',
    emoji: '🏙️',
    category: 'logic',
    tagline: 'Place buildings so the view count matches clues',
    description: 'Fill 1–N in each row and column. Edge clues show how many buildings are visible from that direction. Taller buildings block shorter ones.',
    difficulty: 'hard',
    estimatedMinutes: 10,
    isUnlimited: true,
    hasDailyMode: false,
    mvpPhase: 11,
    hint: 'A clue of 1 means the tallest building is visible first — place the tallest skyscraper at that edge of the row.',
  },
  {
    id: 'takuzu',
    name: 'Takuzu',
    emoji: '01',
    category: 'logic',
    tagline: 'Fill the grid with 0s and 1s following three rules',
    description: 'Each row and column must have equal 0s and 1s. No three consecutive same digits. No two rows or columns identical.',
    difficulty: 'medium',
    estimatedMinutes: 8,
    isUnlimited: true,
    hasDailyMode: false,
    mvpPhase: 11,
    hint: 'Each row and column needs equal 0s and 1s with no three consecutive identical digits. Start with forced cells.',
  },
  {
    id: 'dots-boxes',
    name: 'Dots & Boxes',
    emoji: '⬜',
    category: 'classic',
    tagline: 'Claim boxes by completing their sides',
    description: 'Take turns drawing edges between dots. Complete a box to claim it and take another turn. Beat the AI.',
    difficulty: 'medium',
    estimatedMinutes: 5,
    isUnlimited: true,
    hasDailyMode: false,
    mvpPhase: 11,
    hint: 'Avoid completing the third side of any box until you must — then chain as many boxes together as possible.',
  },
  {
    id: 'logic-grid',
    name: 'Logic Grid',
    emoji: '🧩',
    category: 'logic',
    tagline: 'Use clues to deduce who has what',
    description: 'Read the clues and fill in the logic grid to match each person with their correct attribute. Pure deductive reasoning.',
    difficulty: 'medium',
    estimatedMinutes: 8,
    isUnlimited: true,
    hasDailyMode: false,
    mvpPhase: 11,
    hint: 'Start with the most direct clues (X is or is not Y). Use a grid to track every elimination systematically.',
  },
  // MVP 12
  {
    id: 'word-bingo',
    name: 'Word Bingo',
    emoji: '🎱',
    category: 'word',
    tagline: 'Mark your bingo card as definitions are read',
    description: 'Definitions are called out one by one. Find the matching word on your bingo card and mark it. Get 5 in a row to win.',
    difficulty: 'easy',
    estimatedMinutes: 5,
    isUnlimited: true,
    hasDailyMode: false,
    mvpPhase: 12,
    hint: 'Scan for common word endings (-TION, -ING, -ER) that could complete multiple cells in one go.',
  },
  {
    id: 'vocab-builder',
    name: 'Vocab Builder',
    emoji: '📖',
    category: 'word',
    tagline: 'Match words to their definitions',
    description: 'A definition is shown — pick the correct word from four choices. Build your vocabulary one round at a time.',
    difficulty: 'variable',
    estimatedMinutes: 4,
    isUnlimited: true,
    hasDailyMode: false,
    mvpPhase: 12,
    hint: 'Eliminate answers you are certain are wrong first. Latin and Greek roots (-logy, -phile, -tion) narrow choices fast.',
  },
  {
    id: 'abbreviations',
    name: 'Abbreviations',
    emoji: '🔤',
    category: 'word',
    tagline: 'Guess what the abbreviation stands for',
    description: 'An abbreviation is shown — identify its full form from four options. NASA, ASAP, USB and more. 10 rounds.',
    difficulty: 'easy',
    estimatedMinutes: 3,
    isUnlimited: true,
    hasDailyMode: false,
    mvpPhase: 12,
    hint: 'Say each letter of the abbreviation aloud — the expanded form often sounds just like the initials spoken.',
  },
  {
    id: 'dominoes',
    name: 'Dominoes',
    emoji: '🁢',
    category: 'classic',
    tagline: 'Pair adjacent cells to cover the entire grid',
    description: 'Tap two adjacent cells to pair them as a domino. Cover every cell on the board to win.',
    difficulty: 'medium',
    estimatedMinutes: 5,
    isUnlimited: true,
    hasDailyMode: false,
    mvpPhase: 12,
    hint: 'Place high doubles first — they are hardest to fit later. Build chains from both ends of the layout simultaneously.',
  },
  {
    id: 'shikaku',
    name: 'Shikaku',
    emoji: '▦',
    category: 'logic',
    tagline: 'Divide the grid into rectangles',
    description: 'Partition the grid into rectangles so each contains exactly one number and that number equals the rectangle\'s area.',
    difficulty: 'medium',
    estimatedMinutes: 8,
    isUnlimited: true,
    hasDailyMode: false,
    mvpPhase: 12,
    hint: 'Each number tells you the area of its rectangle. List every possible rectangle size that multiplies to that number.',
  },
  {
    id: 'typeshift',
    name: 'Typeshift',
    emoji: '🔤',
    category: 'word',
    tagline: 'Slide letter columns to form words',
    description: 'Each column contains letters. Slide columns up and down to align letters into valid words. Find the target word to win.',
    difficulty: 'medium',
    estimatedMinutes: 5,
    isUnlimited: true,
    hasDailyMode: false,
    mvpPhase: 12,
    hint: 'Find the longest valid word first — it typically locks the most columns into fixed positions.',
  },
  // MVP 13
  {
    id: 'word-morph',
    name: 'Word Morph',
    emoji: '🔄',
    category: 'word',
    tagline: 'Transform one word into another one letter at a time',
    description: 'Change one letter per step to morph the start word into the target word. Every step must be a valid word.',
    difficulty: 'medium',
    estimatedMinutes: 5,
    isUnlimited: true,
    hasDailyMode: false,
    mvpPhase: 13,
    hint: 'Change one letter at a time and check if a valid word appears. Move toward your target one sound at a time.',
  },
  {
    id: 'emoji-story',
    name: 'Emoji Story',
    emoji: '🎬',
    category: 'word',
    tagline: 'Decode movies and phrases from emoji sequences',
    description: 'A sequence of emojis represents a famous movie, phrase, or concept. Pick the correct answer from four choices.',
    difficulty: 'easy',
    estimatedMinutes: 4,
    isUnlimited: true,
    hasDailyMode: false,
    mvpPhase: 13,
    hint: 'Read the emoji sequence like a sentence. Common story arcs — character, journey, obstacle, resolution — help a lot.',
  },
  {
    id: 'reversi',
    name: 'Reversi',
    emoji: '⬛',
    category: 'classic',
    tagline: 'Outflank your opponent to flip their pieces',
    description: 'Place pieces to flank your opponent\'s and flip them to your color. Control more pieces than the AI when the board fills.',
    difficulty: 'medium',
    estimatedMinutes: 8,
    isUnlimited: true,
    hasDailyMode: false,
    mvpPhase: 13,
    hint: 'Edges and corners are permanent flips — prioritize taking corners. Avoid giving your opponent corner access.',
  },
  {
    id: 'last-letter',
    name: 'Last Letter',
    emoji: '🔗',
    category: 'word',
    tagline: 'Chain words where each starts with the last letter',
    description: 'Enter words where each word starts with the last letter of the previous. Build a 10-word chain without repeating.',
    difficulty: 'medium',
    estimatedMinutes: 5,
    isUnlimited: true,
    hasDailyMode: false,
    mvpPhase: 13,
    hint: 'Keep common letter endings in mind: -E, -T, -N, -S are very common. Steer away from rare endings like -X or -Q.',
  },
  {
    id: 'speed-tap',
    name: 'Speed Tap',
    emoji: '⚡',
    category: 'classic',
    tagline: 'Test your reaction time',
    description: 'Wait for the screen to turn green, then tap as fast as you can. 5 rounds — average under 500ms to win.',
    difficulty: 'variable',
    estimatedMinutes: 2,
    isUnlimited: true,
    hasDailyMode: false,
    mvpPhase: 13,
    hint: 'Relax your hand and let your reflexes lead — tensing up slows your reaction. Tap the center of each target.',
  },
  {
    id: 'number-maze',
    name: 'Number Maze',
    emoji: '🔢',
    category: 'number',
    tagline: 'Navigate the maze visiting numbers in order',
    description: 'Move through a grid and visit numbered cells in ascending order. Plan your path carefully.',
    difficulty: 'medium',
    estimatedMinutes: 5,
    isUnlimited: true,
    hasDailyMode: false,
    mvpPhase: 13,
    hint: 'The target sum tells you which paths stay valid. Eliminate branches that would exceed the total too early.',
  },
  {
    id: 'mirror-puzzle',
    name: 'Mirror Puzzle',
    emoji: '🪞',
    category: 'visual',
    tagline: 'Toggle cells to match the mirrored target',
    description: 'The left half mirrors to the right automatically. Toggle cells on the left side to make the full grid match the target pattern.',
    difficulty: 'medium',
    estimatedMinutes: 5,
    isUnlimited: true,
    hasDailyMode: false,
    mvpPhase: 13,
    hint: 'Fold the grid mentally along the mirror axis. Every cell must be identical to its mirror counterpart.',
  },
  // MVP 14
  {
    id: 'mahjong',
    name: 'Mahjong',
    emoji: '🀄',
    category: 'classic',
    tagline: 'Match pairs of identical tiles to clear the board',
    description: 'Tap matching tile pairs to remove them. Clear all tiles from the board to win.',
    difficulty: 'medium',
    estimatedMinutes: 8,
    isUnlimited: true,
    hasDailyMode: false,
    mvpPhase: 14,
    hint: 'Match tiles that are free on the left or right side and not covered on top. Match high-value tiles early.',
  },
  {
    id: 'checkers',
    name: 'Checkers',
    emoji: '🔴',
    category: 'classic',
    tagline: 'Capture all opponent pieces to win',
    description: 'Move diagonally, jump over opponents to capture their pieces. Reach the other end to crown a king. Beat the AI.',
    difficulty: 'medium',
    estimatedMinutes: 10,
    isUnlimited: true,
    hasDailyMode: false,
    mvpPhase: 14,
    hint: 'Keep pieces on the back row as long as possible — they prevent your opponent from kinging. Trade pieces wisely.',
  },
  {
    id: 'masyu',
    name: 'Masyu',
    emoji: '⭕',
    category: 'logic',
    tagline: 'Draw a loop through all circles',
    description: 'Draw a single closed loop passing through every circle. Black circles require a turn, white circles require going straight.',
    difficulty: 'hard',
    estimatedMinutes: 10,
    isUnlimited: true,
    hasDailyMode: false,
    mvpPhase: 14,
    hint: 'Black circles turn 90° and go straight on both sides of the pearl. White circles go straight through the pearl.',
  },
  {
    id: 'tapa',
    name: 'Tapa',
    emoji: '⬛',
    category: 'logic',
    tagline: 'Shade cells to form a connected wall',
    description: 'Shade cells to form one connected wall. Clue cells show the sizes of consecutive shaded groups in surrounding cells.',
    difficulty: 'hard',
    estimatedMinutes: 10,
    isUnlimited: true,
    hasDailyMode: false,
    mvpPhase: 14,
    hint: 'Tapa segments cannot touch each other diagonally or orthogonally. Work from cells where segments are forced.',
  },
  {
    id: 'fillomino',
    name: 'Fillomino',
    emoji: '🔢',
    category: 'logic',
    tagline: 'Fill regions so each contains N cells with value N',
    description: 'Assign numbers to cells so that each connected region of N cells contains the number N throughout.',
    difficulty: 'hard',
    estimatedMinutes: 12,
    isUnlimited: true,
    hasDailyMode: false,
    mvpPhase: 14,
    hint: 'Each numbered cell anchors a region of that exact size. Same-numbered regions can never touch each other.',
  },
  {
    id: 'acrostic',
    name: 'Acrostic',
    emoji: '📝',
    category: 'word',
    tagline: 'Solve clues whose first letters spell a word',
    description: 'Answer each clue and the first letters of your answers will spell a hidden word. A crossword of a different kind.',
    difficulty: 'medium',
    estimatedMinutes: 8,
    isUnlimited: true,
    hasDailyMode: false,
    mvpPhase: 14,
    hint: 'Fill in answers you are most confident about first. The first letters of each answer spell the hidden quote.',
  },
  {
    id: 'syllable-split',
    name: 'Syllable Split',
    emoji: '🗣️',
    category: 'word',
    tagline: 'Choose the correct syllable breakdown',
    description: 'A word is shown — pick the correct way to split it into syllables from four choices. Great for language learners.',
    difficulty: 'easy',
    estimatedMinutes: 3,
    isUnlimited: true,
    hasDailyMode: false,
    mvpPhase: 14,
    hint: 'Place your hand under your chin and count the drops as you say the word — each drop is one syllable.',
  },
  {
    id: 'word-parts',
    name: 'Word Parts',
    emoji: '🧩',
    category: 'word',
    tagline: 'Combine prefix, root, and suffix to build words',
    description: 'Select the correct prefix and suffix for the given root word to form a valid compound word.',
    difficulty: 'medium',
    estimatedMinutes: 4,
    isUnlimited: true,
    hasDailyMode: false,
    mvpPhase: 14,
    hint: 'Many English words are built from Latin or Greek roots. Port = carry, Graph = write, Phon = sound.',
  },
  {
    id: 'phonetic-spelling',
    name: 'Phonetic Spelling',
    emoji: '📡',
    category: 'classic',
    tagline: 'Match letters to their NATO phonetic words',
    description: 'A letter is shown — pick its NATO phonetic alphabet word. Alpha, Bravo, Charlie... how well do you know them?',
    difficulty: 'easy',
    estimatedMinutes: 3,
    isUnlimited: true,
    hasDailyMode: false,
    mvpPhase: 14,
    hint: 'Transcribe each sound you hear, not each letter you see. Phone has an F sound — /foʊn/ not P-H-O-N-E.',
  },
  {
    id: 'emoji-sudoku',
    name: 'Emoji Sudoku',
    emoji: '🐶',
    category: 'number',
    tagline: 'Sudoku with emoji instead of numbers',
    description: 'A 4×4 sudoku where numbers are replaced by cute emojis. Same rules — no repeats in rows, columns, or 2×2 boxes.',
    difficulty: 'easy',
    estimatedMinutes: 5,
    isUnlimited: true,
    hasDailyMode: false,
    mvpPhase: 14,
    hint: 'Treat each emoji as a number — every row, column, and box must contain each symbol exactly once.',
  },
  // MVP 15
  {
    id: 'letter-drop',
    name: 'Letter Drop',
    emoji: '⬇️',
    category: 'word',
    tagline: 'Cycle letter columns to form target words',
    description: 'Each column contains stacked letters. Tap the arrow to cycle down. Line up letters across columns to form valid words and collect them.',
    difficulty: 'medium',
    estimatedMinutes: 5,
    isUnlimited: true,
    hasDailyMode: false,
    mvpPhase: 15,
    hint: 'Watch the descent speed and plan your placement 2–3 tiles ahead of the current falling piece.',
  },
  {
    id: 'word-maze',
    name: 'Word Maze',
    emoji: '🗺️',
    category: 'word',
    tagline: 'Trace adjacent letters to find hidden words',
    description: 'Tap adjacent letters in the grid to spell words. Letters can connect in any direction. Find 3 words to complete the puzzle.',
    difficulty: 'medium',
    estimatedMinutes: 5,
    isUnlimited: true,
    hasDailyMode: false,
    mvpPhase: 15,
    hint: 'Navigate using only valid words. Longer words cover more ground — plan ahead to avoid dead ends.',
  },
  {
    id: 'wordsmiths-duel',
    name: 'Wordsmiths Duel',
    emoji: '🏆',
    category: 'word',
    tagline: 'Battle the AI to form words from a shared pool',
    description: 'Take turns picking letters from a shared pool to form words. Score points equal to the number of letters used. Outscore the AI to win.',
    difficulty: 'medium',
    estimatedMinutes: 8,
    isUnlimited: true,
    hasDailyMode: false,
    mvpPhase: 15,
    hint: 'Balance speed and accuracy. A moment to think is faster than recovering from a wrong answer penalty.',
  },
  {
    id: 'gravity-blocks',
    name: 'Gravity Blocks',
    emoji: '🔴',
    category: 'classic',
    tagline: 'Drop blocks to connect 4 in a row',
    description: 'Tap a column to drop a block. Connect 4 of your blocks horizontally, vertically, or diagonally before the AI does.',
    difficulty: 'medium',
    estimatedMinutes: 5,
    isUnlimited: true,
    hasDailyMode: false,
    mvpPhase: 15,
    hint: 'Create horizontal lines to clear them. Keep your stack flat and avoid building tall isolated columns.',
  },
  {
    id: 'daily-challenge',
    name: 'Daily Challenge',
    emoji: '🌟',
    category: 'classic',
    tagline: 'Three fresh mini-challenges every day',
    description: 'Each day brings a fresh rotation of word scrambles, math problems, and trivia. Complete all three for a perfect score.',
    difficulty: 'variable',
    estimatedMinutes: 5,
    isUnlimited: false,
    hasDailyMode: true,
    mvpPhase: 15,
    hint: 'Read all parts of the challenge before starting — some steps connect, and knowing the end helps you plan.',
  },
];

export const getGamesByCategory = (category: string): GameDefinition[] =>
  GAMES.filter(g => g.category === category);

export const getGamesByMVP = (maxPhase: number): GameDefinition[] =>
  GAMES.filter(g => g.mvpPhase <= maxPhase);
