#!/usr/bin/env node
/**
 * Fetches a large English word list and filters it to valid 5-letter words.
 * Source: dwyl/english-words (~370k words, public domain)
 *
 * Run from the project root:
 *   node scripts/fetchWordBank.js
 *
 * This will overwrite src/games/wordguess/wordBank.ts with the full list.
 * Expected output: ~10,000–11,000 five-letter words.
 */

const https = require('https');
const fs = require('fs');
const path = require('path');

const SOURCE_URL =
  'https://raw.githubusercontent.com/dwyl/english-words/master/words_alpha.txt';

const OUT_PATH = path.join(
  __dirname,
  '../src/games/wordguess/wordBank.ts',
);

// Words to always exclude (offensive, slurs, etc.)
const BLOCKLIST = new Set([]);

console.log('Downloading word list from GitHub...');

https.get(SOURCE_URL, res => {
  if (res.statusCode !== 200) {
    console.error(`HTTP ${res.statusCode} — download failed`);
    process.exit(1);
  }

  let raw = '';
  res.on('data', chunk => (raw += chunk));
  res.on('end', () => {
    const words = [
      ...new Set(
        raw
          .split('\n')
          .map(w => w.trim().toLowerCase())
          .filter(w => w.length === 5 && /^[a-z]{5}$/.test(w) && !BLOCKLIST.has(w)),
      ),
    ].sort();

    const content = `// ${words.length} five-letter words — auto-generated by scripts/fetchWordBank.js
// Do not edit manually. Re-run the script to refresh.
export const WORD_BANK: string[] = ${JSON.stringify(words)};

export const WORD_SET = new Set(WORD_BANK);
`;

    fs.writeFileSync(OUT_PATH, content, 'utf8');
    console.log(`✓ Written ${words.length.toLocaleString()} words to ${OUT_PATH}`);
    console.log('  Restart Metro bundler to pick up the new file.');
  });
}).on('error', err => {
  console.error('Network error:', err.message);
  process.exit(1);
});
